stages:
- stage: Build
  variables:
  - group: Bl0g.Infrastructure.Build
  jobs:
  - job: BuildJob
    pool:
        vmImage: 'windows-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.ARM.Source.Path)
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  variables:
    - group: Bl0g
    - group: Bl0g.Production
    - group: Bl0g.Infrastructure.Bootstrap.Release
  jobs:
  - deployment: Deploy
    pool:
        vmImage: 'windows-latest'
    environment: 'blog-deployment'
    strategy:
        runOnce:
            deploy:
                steps:
                - task: AzureResourceGroupDeployment@2
                  inputs:
                    azureSubscription: 'blog-connection'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(Release.ResourceGroup.Name)
                    location: $(Release.Location)
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Release.Template.Path)'
                    csmParametersFile: '$(Release.Template.Parameters.Path)'
                    overrideParameters: '-storagename "$(Release.Template.Storage.Name)" -env "$(Env)"'
                    deploymentMode: 'Incremental'
                - task: AzureFileCopy@3
                  inputs:
                    SourcePath: '$(Release.Template.Arm.Source.Path)'
                    azureSubscription: 'blog-connection'
                    Destination: 'AzureBlob'
                    storage: '$(Release.Template.Storage.Name)$(Env)'
                    ContainerName: 'arm'
                    outputStorageUri: 'ArmStorageUri'
                    outputStorageContainerSasToken: 'ArmStorageSasToken'
                - task: AzureResourceGroupDeployment@2
                  inputs:
                    azureSubscription: 'blog-connection'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: '$(Release.ResourceGroup.Name)'
                    location: '$(Release.Location)'
                    templateLocation: 'URL of the file'
                    csmFileLink: '$(ArmStorageUri)maintemplate.json$(ArmStorageSasToken)'
                    csmParametersFileLink: '$(ArmStorageUri)maintemplate.parameters.json$(ArmStorageSasToken)'
                    overrideParameters: '-storageSasToken "$(ArmStorageSasToken)" -storageUri "$(ArmStorageUri)" -mssqlAdminLogin "$(Database.Login)" -mssqlAdminPassword "$(Database.Password)"'
                    deploymentMode: 'Incremental'
