stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
        vmImage: 'windows-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'src/Bl0g.Infrastructure.Azure/Bl0g.Infrastructure.Azure'
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
        vmImage: 'windows-latest'
    environment: 'blog-deployment-dev'
    strategy:
        runOnce:
            deploy:
                steps:
                - script: echo deploy ARM template