variables:
- group: Bl0g.Infrastructure
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
        vmImage: 'windows-latest'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(ARM.Source.Path)
        Contents: '**\*.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
