version: '3'
services:
  spa:
    build:
      context: ../../../Bl0g.SPA.WebApp/src/Bl0g.SPA.WebApp/Bl0g.SPA.WebApp/
    ports:
    - "6000:443"
    - "7000:80"
    environment: 
      CONTENT_API_SERVICE_HOST=""
      CONTENT_API_SERVICE_PORT=""
  content-api:
    build:
      context: ../../../Bl0g.Content.WebApi/src/Bl0g.Content.WebApi/
    ports:
    - "8000:80"
